services:
  # Backend API Service
  - type: web
    name: envanter-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: envanter-db
          property: connectionString

  # Frontend Static Site
  - type: web
    name: envanter-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://envanter-api.onrender.com

# PostgreSQL Database
databases:
  - name: envanter-db
    plan: free